// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "gin-splitwise/internal/group/model"
)

// GroupMemberDB is an autogenerated mock type for the GroupMemberDB type
type GroupMemberDB struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, member
func (_m *GroupMemberDB) Add(ctx context.Context, member *model.GroupMember) error {
	ret := _m.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GroupMember) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByGroupID provides a mock function with given fields: ctx, id
func (_m *GroupMemberDB) FindByGroupID(ctx context.Context, id uint) ([]model.GroupMember, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByGroupID")
	}

	var r0 []model.GroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]model.GroupMember, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []model.GroupMember); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, id
func (_m *GroupMemberDB) FindByUserID(ctx context.Context, id uint) ([]model.GroupMember, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.GroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]model.GroupMember, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []model.GroupMember); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, id
func (_m *GroupMemberDB) Remove(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGroupMemberDB creates a new instance of GroupMemberDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupMemberDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupMemberDB {
	mock := &GroupMemberDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
